spring.application.name=forohub-alura
spring.datasource.url=jdbc:postgresql://localhost/forohub-alura
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

api.security.token.secret=${JWT_SECRET:1234567890}
